# Form implementation generated from reading ui file 'ui_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QWidget
import sys


# Ui_Form由ui文件生成
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setBaseSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "pyqt6实战"))
        self.label.setText(_translate("Form", "冲冲冲"))


if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = QWidget()
    Ui_Form().setupUi(window)
    window.show()

    sys.exit(app.exec())
